highlight improvements

diff --git a/templates/sh b/templates/sh
--- a/templates/sh
+++ b/templates/sh
@@ -3,6 +3,21 @@
 echo "This is a template file, not executable"
 exit 9
 
+# ---------- Pre ----------
+
+# If a program exits with an error, halt the script
+##- {
+set -o errexit
+##- }
+
+# If a var doesn't exist, and is referenced, that is an error to halt for
+#
+# Note, however, that things like 'if [[ $1 == "" ]]' will fail, so this is less
+# useful than it could be
+##- {
+set -o nounset
+##- }
+
 # ---------- Die ----------
 #
 # Use die like:
@@ -10,12 +25,52 @@ exit 9
 #     [[ $# > 0 ]] || die "Gimme an arg" 99
 #
 
+##- {
+
 die() {
   echo $1
   xcode="99"
   [[ $# > 1 ]] && xcode="$2"
   exit $xcode
 }
+
+[[ $# > 0 ]] || die "Gimme an arg" 99
+
+check_or_die()
+{
+  which $1 > /dev/null || die "$1 not found"
+}
+
+check_or_die node 
+
+##- }
+
+# ---------- Paramater parsing ----------
+#
+# Note:
+# * The below handling for '*' should be changed.
+#
+# Limitations:
+# 1. The flags must come before other args
+# 1. Must use '--' to signal 'no more flags'
+
+foo="default foo value"
+bar="5"
+fubar="aaaaaa"
+
+##- {
+for arg in "$@"; do case $arg in
+  --foo=*)      foo="${arg#*=}";      shift;;
+  --bar=*)      bar="${arg#*=}";      shift;;
+  --fu-bar=*)   fubar="${arg#*=}";    shift;;
+  --baz=*)      baz="${arg#*=}";      shift;;
+
+  --)                                 shift; break;;
+  *)            echo "$arg";          shift;;
+esac; done
+
+[[ -z "$baz" ]] || die "Must provide --baz=xyz"
+##- }
 
 # ---------- Dependencies ----------
 
@@ -28,6 +83,9 @@ which example > /dev/null || die "example required"
 #
 # Replace the installer command (the npm install line)
 #    sudo apt-get install -y ${UTIL_NAME}
+
+##- {
+
 check_and_install()
 {
   UTIL_NAME="$1"
@@ -38,6 +96,8 @@ check_and_install()
   fi
 }
 
+##- }
+
 check_for "grunt" "grunt-cli"
 check_for "bower"
 
@@ -46,17 +106,6 @@ if ! dpkg -s example 2> /dev/null > /dev/null; then
   sudo apt-get install example
 fi
 
-
-# ---------- Pre ----------
-
-# If a program exits with an error, halt the script
-set -o errexit
-
-# If a var doesn't exist, and is referenced, that is an error to halt for
-#
-# Note, however, that things like 'if [[ $1 == "" ]]' will fail, so this is less
-# useful than it could be
-set -o nounset
 
 # ---------- Idioms ----------
 
@@ -69,31 +118,6 @@ set -o nounset
 if [[ -n "$user" ]]; then
   cmd="${cmd} --user ${user}"
 fi
-
-# ---------- Paramater parsing ----------
-
-# Note:
-# * The below handling for '*' should be changed.
-#
-# Limitations:
-# 1. The flags must come before other args
-# 1. Must use '--' to signal 'no more flags'
-
-foo="default foo value"
-bar="5"
-fubar="aaaaaa"
-
-for arg in "$@"; do case $arg in
-  --foo=*)     foo="${arg#*=}";     shift;;
-  --bar=*)     bar="${arg#*=}";     shift;;
-  --fu-bar=*)  fubar="${arg#*=}";   shift;;
-  --baz=*)     baz="${arg#*=}";     shift;;
-
-  --)                               shift; break;;
-  *)           echo "$arg";         shift;;
-esac; done
-
-[[ -z "$baz" ]] || die "Must provide --baz=xyz"
 
 
 
